version: 2
updates:
  - package-ecosystem: pip
    directory: /ml-close-loop-be
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /ml-close-loop-fe
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /ml-close-loop-be
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /ml-close-loop-fe
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
