"""us_013_add_indexes_on_foreign_keys

Revision ID: 190c9e1c557c
Revises: 82a8dede6a78
Create Date: 2026-09-02 07:59:02.658668

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "190c9e1c557c"
down_revision: Union[str, Sequence[str], None] = "82a8dede6a78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_model_versions_model_id"), "model_versions", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_versions_training_run_id"),
        "model_versions",
        ["training_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_promotion_decisions_model_version_id"),
        "promotion_decisions",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_runs_dataset_version_id"),
        "training_runs",
        ["dataset_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_validation_reports_dataset_version_id"),
        "validation_reports",
        ["dataset_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_validation_reports_dataset_version_id"),
        table_name="validation_reports",
    )
    op.drop_index(
        op.f("ix_training_runs_dataset_version_id"), table_name="training_runs"
    )
    op.drop_index(
        op.f("ix_promotion_decisions_model_version_id"),
        table_name="promotion_decisions",
    )
    op.drop_index(
        op.f("ix_model_versions_training_run_id"), table_name="model_versions"
    )
    op.drop_index(op.f("ix_model_versions_model_id"), table_name="model_versions")
    # ### end Alembic commands ###
