"""add model_drift_checks table

Revision ID: 1ce554582542
Revises: a543e4c9830a
Create Date: 2026-09-11 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1ce554582542"
down_revision: Union[str, Sequence[str], None] = "a543e4c9830a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Issue #136: periodic post-promotion drift-check history, kept separate from
    `model_versions`' own (single-snapshot) evaluation columns. Hand-written rather than
    autogenerated: this repo has pre-existing, unrelated schema drift (see the NOTE in
    d32c491e39a6_add_notifications_table.py) that autogenerate would otherwise fold into this
    migration.
    """
    op.create_table(
        "model_drift_checks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("eval_set_id", sa.String(), nullable=True),
        sa.Column("eval_set_version", sa.Integer(), nullable=True),
        sa.Column("eval_loss_trend", sa.JSON(), nullable=True),
        sa.Column("qualitative_comparison", sa.JSON(), nullable=True),
        sa.Column("general_domain_regression_check", sa.JSON(), nullable=True),
        sa.Column(
            "new_regression_detected",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_drift_checks_model_version_id"),
        "model_drift_checks",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_drift_checks_trigger"),
        "model_drift_checks",
        ["trigger"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_model_drift_checks_trigger"), table_name="model_drift_checks"
    )
    op.drop_index(
        op.f("ix_model_drift_checks_model_version_id"),
        table_name="model_drift_checks",
    )
    op.drop_table("model_drift_checks")
