"""add_compute_resources_table_and_fk

Revision ID: 213418ebfc30
Revises: 0f6d1c9e4a2f
Create Date: 2026-09-09 15:47:48.513337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "213418ebfc30"
down_revision: Union[str, Sequence[str], None] = "0f6d1c9e4a2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compute_resources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("environment", sa.String(), nullable=False),
        sa.Column("provider_type", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=True),
        sa.Column("gpu_info", sa.JSON(), nullable=True),
        sa.Column("ssh_host", sa.String(), nullable=True),
        sa.Column("ssh_port", sa.Integer(), nullable=True),
        sa.Column("ssh_username", sa.String(), nullable=True),
        sa.Column("credential_ref", sa.String(), nullable=True),
        sa.Column("is_healthy", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_compute_resources_name"), "compute_resources", ["name"], unique=True
    )
    # SQLite does not support ALTER TABLE to add FK constraints; use batch mode
    # to recreate the table with the new column and FK (issue #75).
    with op.batch_alter_table("training_runs") as batch_op:
        batch_op.add_column(
            sa.Column("compute_resource_id", sa.Integer(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_training_runs_compute_resource_id"),
            ["compute_resource_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_training_runs_compute_resource_id",
            "compute_resources",
            ["compute_resource_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("training_runs") as batch_op:
        batch_op.drop_constraint(
            "fk_training_runs_compute_resource_id", type_="foreignkey"
        )
        batch_op.drop_index(
            batch_op.f("ix_training_runs_compute_resource_id"),
            table_name="training_runs",
        )
        batch_op.drop_column("compute_resource_id")
    op.drop_index(op.f("ix_compute_resources_name"), table_name="compute_resources")
    op.drop_table("compute_resources")
    # ### end Alembic commands ###
