"""US-011 add model and model_version tables

Revision ID: 29f1f96e3ea1
Revises: 249fbe20ec68
Create Date: 2026-08-28 09:29:28.155365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f1f96e3ea1'
down_revision: Union[str, Sequence[str], None] = '249fbe20ec68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('model_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('training_run_id', sa.String(), nullable=False),
    sa.Column('base_model', sa.String(), nullable=False),
    sa.Column('training_config', sa.JSON(), nullable=False),
    sa.Column('dataset_validation_report_ref', sa.String(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('promotion_decision_ref', sa.String(), nullable=True),
    sa.Column('previous_model_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.training_run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version', name='uq_model_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_versions')
    op.drop_table('models')
    # ### end Alembic commands ###
