"""US-004 add validation report model

Revision ID: 4e83458e8145
Revises: b6079426a4fc
Create Date: 2026-08-27 16:39:03.744864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e83458e8145'
down_revision: Union[str, Sequence[str], None] = 'b6079426a4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('rule_set_version', sa.String(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('status_counts', sa.JSON(), nullable=False),
    sa.Column('warnings_summary', sa.JSON(), nullable=False),
    sa.Column('dataset_statistics', sa.JSON(), nullable=False),
    sa.Column('gate_decision', sa.String(), nullable=False),
    sa.Column('gate_reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_reports')
    # ### end Alembic commands ###
