"""US-015 add promotion decisions table

Revision ID: de0f2f594aa9
Revises: e8568ffabe01
Create Date: 2026-08-28 09:54:20.042362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0f2f594aa9'
down_revision: Union[str, Sequence[str], None] = 'e8568ffabe01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_decisions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('rollback_of_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotion_decisions')
    # ### end Alembic commands ###
