"""US-018 add deployments table

Revision ID: eb8695aecf69
Revises: de0f2f594aa9
Create Date: 2026-08-28 10:14:26.531185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8695aecf69'
down_revision: Union[str, Sequence[str], None] = 'de0f2f594aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_version', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployments')
    # ### end Alembic commands ###
